# Generated by Django 4.2.6 on 2023-10-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.BigIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(default='Tashkent', max_length=150)),
                ('email', models.CharField(default=' ', max_length=200)),
                ('number', models.BigIntegerField(default=10)),
                ('date', models.DateField(default='24-10-2023')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='24-10-2023')),
                ('owner', models.CharField(max_length=100)),
                ('total_price', models.BigIntegerField(default=1000)),
                ('payment', models.CharField(default='payment', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='market.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.BigIntegerField(default=1000)),
                ('start_date', models.DateField(default='24-10-2023')),
                ('end_date', models.DateField(default='24-10-2023')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='market.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField(default='24-10-2023')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.productmodel')),
                ('shop_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_card', to='market.shopcardmodel')),
            ],
        ),
    ]
